export const products = [
  {
    id: 1234,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    location: {
      city: "Location 1",
      postalCode: "12345",
      country: "USA",
    },

    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    shelfLife: 10,
    supplier: {
      id: 1,
      name: "Supplier 1",
      phone: "1234567890",
      email: "supplier@email.com",
    },
    custodianId: {
      id: 1,
      name: "Custodian 1",
      email: "custodian@gmail.com",
      phone: "1234567890",
    },
    safetyStock: 600,
  },
  {
    id: 1234,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    location: {
      city: "Location 1",
      postalCode: "12345",
      country: "USA",
    },

    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    shelfLife: 10,
    supplier: {
      id: 1,
      name: "Supplier 1",
      phone: "1234567890",
      email: "supplier@email.com",
    },
    custodianId: {
      id: 1,
      name: "Custodian 1",
      email: "custodian@gmail.com",
      phone: "1234567890",
    },
    safetyStock: 600,
  },
  {
    id: 1234,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    location: {
      city: "Location 1",
      postalCode: "12345",
      country: "USA",
    },

    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    shelfLife: 10,
    supplier: {
      id: 1,
      name: "Supplier 1",
      phone: "1234567890",
      email: "supplier@email.com",
    },
    custodianId: {
      id: 1,
      name: "Custodian 1",
      email: "custodian@gmail.com",
      phone: "1234567890",
    },
    safetyStock: 600,
  },
  {
    id: 1234,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    location: {
      city: "Location 1",
      postalCode: "12345",
      country: "USA",
    },

    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    shelfLife: 10,
    supplier: {
      id: 1,
      name: "Supplier 1",
      phone: "1234567890",
      email: "supplier@email.com",
    },
    custodianId: {
      id: 1,
      name: "Custodian 1",
      email: "custodian@gmail.com",
      phone: "1234567890",
    },
    safetyStock: 600,
  },
];
