export const products = [
  {
    id: 1234,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    supplierId: 1,
    custodianId: 1,
  },
  {
    id: 12445,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    supplierId: 1,
    custodianId: 1,
  },
  {
    id: 12455,
    name: "Product 1",
    description: "Product 1 description",
    createdOn: "2021-01-01",
    priceUSD: 100,
    quantity: 10,
    colour: "red",
    size: "M",
    weight: 100,
    unitOfMeasure: "kg",
    supplierId: 1,
    custodianId: 1,
  },
];
